
#Install packages
- hosts: all
  become: yes
  tasks:
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Install a list of packages
      yum:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - unzip
        - perl
        - vim-enhanced

    - name: remove the firewalld package	
      yum:	
        name: firewalld	
        state: absent

    - name: remove packer symbolic link
      file:
        state: absent
        path: "/usr/sbin/packer"


    - name: Download rke
      get_url:
        url: https://github.com/rancher/rke/releases/download/v1.1.2/rke_linux-amd64
        dest: /usr/local/bin/rke
        mode: '0775'
