steps:

  - name: "Validate packer configuration"
    plugins:
      docker-compose:
        pull: packer-validate
        run: packer-validate
    agents:
      vm: "true"
      home: "true"

  - wait

  - name: "Force build packer image"
    plugins:
      docker-compose:
        pull: packer-build
        run: packer-build
    agents:
      vm: "true"
      home: "true"
